# 应用服务 WEB 访问端口
server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://192.168.47.12:3306/mybatisplus?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root@123456

logging:
  level:
    com.yb.mybatisplus: debug
  pattern:
    dateformat: MM:dd HH:mm:ss

mybatis-plus:
  mybatis-plus.type-aliases-package: com.yb.mybatisplus.pojo
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
    # 是否开启驼峰命名和下划线映射
    map-underscore-to-camel-case: true
    # 是否开启二级缓存
    cache-enabled: false
  global-config:
    db-config:
      # id 默认为雪花算法生成，现改为自增长，实体类就不需要增加 type = IdType.AUTO 属性了
#      id-type: auto
      # 更新策略，只更新非空字段
      update-strategy: not_null
